# Generated by Django 3.2.5 on 2021-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('mpg', models.CharField(max_length=20)),
                ('cylinders', models.CharField(max_length=20)),
                ('displacement', models.CharField(max_length=20)),
                ('horsepower', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('acceleration', models.CharField(max_length=20)),
                ('model_year', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
            ],
        ),
    ]
