# Generated by Django 2.2.13 on 2021-07-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_portfolio', '0003_alter_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
